name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Prevent running this on forks
    if: github.repository_owner == 'zerodytrash'
    runs-on: ubuntu-latest

    steps:
      - name: Setup NodeJS
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run check-format
