name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# Prevent all permissions from being set, just use the ones we need.
permissions:
  contents: read

# Cancel in-progress runs on new commits.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Format:
    # Prevent running this on forks
    if: github.repository_owner == 'zerodytrash'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npm run check-format
