# This workflow will automatically create a new release

name: Build & Create Release

on: [ ]

jobs:
  buildandrelease:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build
    
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Test Build"
        files: dist/Simple-YouTube-Age-Restriction-Bypass.user.js
